#!/bin/bash

#Define the storage directory

OUTPUT_DIR="/storage/emulated/0/Termux/TermuxAudio"

#Create the directory if it does not exist

mkdir -p /storage/emulated/0/Termux
mkdir -p "$OUTPUT_DIR"

#Define the output file name

FILENAME="$(date '+%Y-%m-%d_%H-%M-%S').aac"
OUTPUT_FILE="$OUTPUT_DIR/$FILENAME"

#Send a notification

termux-notification --id 57 \
  --ongoing \
  --title "Recording in progress" \
  --content "Click to stop recording" \
  --action "termux-microphone-record -q && termux-notification-remove 57" \
  --on-delete "bash ~/.shortcuts/tasks/Microphone"

#Start recording

echo "Recording in progress..."
termux-microphone-record -f "$OUTPUT_FILE" -e aac -r 44100 -b 128 -c 2 -d